// namesData.ts
export interface Name {
  id: string; // 1‑based string id so FlatList keyExtractor can use it directly
  name: string; // transliterated Arabic
  meaning: string;
}

export const namesData: Name[] = [
  {id: '1', name: 'Ar‑Rahman', meaning: 'The Most or Entirely Merciful'},
  {id: '2', name: 'Ar‑Raheem', meaning: 'The Bestower of Mercy'},
  {id: '3', name: 'Al‑Malik', meaning: 'The King and Owner of Dominion'},
  {id: '4', name: 'Al‑Quddus', meaning: 'The Absolutely Pure'},
  {id: '5', name: 'As‑Salam', meaning: 'The Perfection and Source of Peace'},
  {id: '6', name: 'Al‑Mu’min', meaning: 'The Giver of Security and Faith'},
  {id: '7', name: 'Al‑Muhaymin', meaning: 'The Guardian, the Overseer'},
  {id: '8', name: 'Al‑Azeez', meaning: 'The All‑Mighty'},
  {id: '9', name: 'Al‑Jabbar', meaning: 'The Compeller, the Restorer'},
  {id: '10', name: 'Al‑Mutakabbir', meaning: 'The Supreme, the Majestic'},
  {id: '11', name: 'Al‑Khaliq', meaning: 'The Creator'},
  {id: '12', name: 'Al‑Baariʼ', meaning: 'The Originator'},
  {id: '13', name: 'Al‑Musawwir', meaning: 'The Fashioner'},
  {id: '14', name: 'Al‑Ghaffaar', meaning: 'The All‑Forgiving'},
  {id: '15', name: 'Al‑Qahhaar', meaning: 'The Subduer, the Ever‑Dominating'},
  {id: '16', name: 'Al‑Wahhaab', meaning: 'The Giver of Gifts'},
  {id: '17', name: 'Ar‑Razzaaq', meaning: 'The Provider'},
  {id: '18', name: 'Al‑Fattaah', meaning: 'The Opener, the Granter of Success'},
  {id: '19', name: 'Al‑‘Aleem', meaning: 'The All‑Knowing'},
  {id: '20', name: 'Al‑Qaabid', meaning: 'The Withholder'},
  {id: '21', name: 'Al‑Baasit', meaning: 'The Extender'},
  {id: '22', name: 'Al‑Khaafid', meaning: 'The Reducer'},
  {id: '23', name: 'Ar‑Raafiʿ', meaning: 'The Exalter'},
  {id: '24', name: 'Al‑Muʿizz', meaning: 'The Honourer'},
  {id: '25', name: 'Al‑Muzil', meaning: 'The Dishonourer'},
  {id: '26', name: 'As‑Sameeʿ', meaning: 'The All‑Hearing'},
  {id: '27', name: 'Al‑Baseer', meaning: 'The All‑Seeing'},
  {id: '28', name: 'Al‑Hakam', meaning: 'The Judge'},
  {id: '29', name: 'Al‑‘Adl', meaning: 'The Utterly Just'},
  {id: '30', name: 'Al‑Lateef', meaning: 'The Subtle, the Most Gentle'},
  {id: '31', name: 'Al‑Khabeer', meaning: 'The All‑Aware'},
  {id: '32', name: 'Al‑Haleem', meaning: 'The Forbearing'},
  {id: '33', name: 'Al‑‘Azeem', meaning: 'The Magnificent'},
  {id: '34', name: 'Al‑Ghafoor', meaning: 'The Forgiver'},
  {id: '35', name: 'Ash‑Shakoor', meaning: 'The Most Appreciative'},
  {id: '36', name: 'Al‑‘Aliyy', meaning: 'The Most High'},
  {id: '37', name: 'Al‑Kabeer', meaning: 'The Most Great'},
  {id: '38', name: 'Al‑Hafeezh', meaning: 'The Preserver'},
  {id: '39', name: 'Al‑Muqeet', meaning: 'The Sustainer'},
  {id: '40', name: 'Al‑Haseeb', meaning: 'The Reckoner'},
  {id: '41', name: 'Al‑Jaleel', meaning: 'The Majestic'},
  {id: '42', name: 'Al‑Kareem', meaning: 'The Generous'},
  {id: '43', name: 'Ar‑Raqeeb', meaning: 'The Watchful'},
  {id: '44', name: 'Al‑Mujeeb', meaning: 'The Responsive'},
  {id: '45', name: 'Al‑Waasiʿ', meaning: 'The All‑Encompassing'},
  {id: '46', name: 'Al‑Hakeem', meaning: 'The All‑Wise'},
  {id: '47', name: 'Al‑Wadud', meaning: 'The Loving'},
  {id: '48', name: 'Al‑Majeed', meaning: 'The Glorious'},
  {id: '49', name: 'Al‑Baʿith', meaning: 'The Resurrector'},
  {id: '50', name: 'Ash‑Shaheed', meaning: 'The Witness'},
  {id: '51', name: 'Al‑Haqq', meaning: 'The Truth'},
  {id: '52', name: 'Al‑Wakeel', meaning: 'The Trustee'},
  {id: '53', name: 'Al‑Qawiyy', meaning: 'The All‑Strong'},
  {id: '54', name: 'Al‑Mateen', meaning: 'The Firm'},
  {id: '55', name: 'Al‑Waliyy', meaning: 'The Protecting Friend'},
  {id: '56', name: 'Al‑Hameed', meaning: 'The Praiseworthy'},
  {id: '57', name: 'Al‑Muhsi', meaning: 'The All‑Enumerating'},
  {id: '58', name: 'Al‑Mubdi', meaning: 'The Originator'},
  {id: '59', name: 'Al‑Muʿeed', meaning: 'The Restorer'},
  {id: '60', name: 'Al‑Muhyi', meaning: 'The Giver of Life'},
  {id: '61', name: 'Al‑Mumeet', meaning: 'The Creator of Death'},
  {id: '62', name: 'Al‑Hayy', meaning: 'The Ever‑Living'},
  {id: '63', name: 'Al‑Qayyoom', meaning: 'The Sustainer'},
  {id: '64', name: 'Al‑Waajid', meaning: 'The Perceiver'},
  {id: '65', name: 'Al‑Maajid', meaning: 'The Illustrious'},
  {id: '66', name: 'Al‑Waahid', meaning: 'The One'},
  {id: '67', name: 'Al‑Ahad', meaning: 'The Unique'},
  {id: '68', name: 'As‑Samad', meaning: 'The Eternal'},
  {id: '69', name: 'Al‑Qaadir', meaning: 'The Omnipotent'},
  {id: '70', name: 'Al‑Muqtadir', meaning: 'The All‑Determining'},
  {id: '71', name: 'Al‑Muqaddim', meaning: 'The Expediter'},
  {id: '72', name: 'Al‑Mu’akhkhir', meaning: 'The Delayer'},
  {id: '73', name: 'Al‑Awwal', meaning: 'The First'},
  {id: '74', name: 'Al‑Aakhir', meaning: 'The Last'},
  {id: '75', name: 'Az‑Zaahir', meaning: 'The Manifest'},
  {id: '76', name: 'Al‑Baatin', meaning: 'The Hidden'},
  {id: '77', name: 'Al‑Waali', meaning: 'The Sole Governor'},
  {id: '78', name: 'Al‑Mutaʿaali', meaning: 'The Self‑Exalted'},
  {id: '79', name: 'Al‑Barr', meaning: 'The Source of All Goodness'},
  {id: '80', name: 'At‑Tawwaab', meaning: 'The Ever‑Pardoning'},
  {id: '81', name: 'Al‑Muntaqim', meaning: 'The Avenger'},
  {id: '82', name: 'Al‑‘Afuww', meaning: 'The Pardoner'},
  {id: '83', name: 'Ar‑Ra’oof', meaning: 'The Most Kind'},
  {id: '84', name: 'Maalik‑ul‑Mulk', meaning: 'Master of the Kingdom'},
  {id: '85', name: 'Dhul‑Jalaali Wal‑Ikram', meaning: 'Lord of Glory & Honour'},
  {id: '86', name: 'Al‑Muqsit', meaning: 'The Just One'},
  {id: '87', name: 'Al‑Jaamiʿ', meaning: 'The Gatherer'},
  {id: '88', name: 'Al‑Ghaniyy', meaning: 'The Self‑Sufficient'},
  {id: '89', name: 'Al‑Mughni', meaning: 'The Enricher'},
  {id: '90', name: 'Al‑Maaniʿ', meaning: 'The Withholder'},
  {id: '91', name: 'Ad‑Daarr', meaning: 'The Distresser'},
  {id: '92', name: 'An‑Naafiʿ', meaning: 'The Benefactor'},
  {id: '93', name: 'An‑Noor', meaning: 'The Light'},
  {id: '94', name: 'Al‑Haadi', meaning: 'The Guide'},
  {id: '95', name: 'Al‑Badiʿ', meaning: 'The Incomparable Originator'},
  {id: '96', name: 'Al‑Baaqi', meaning: 'The Everlasting'},
  {id: '97', name: 'Al‑Waarith', meaning: 'The Inheritor'},
  {id: '98', name: 'Ar‑Rasheed', meaning: 'The Guide to the Right Path'},
  {id: '99', name: 'As‑Saboor', meaning: 'The Patient'},
];
